insert into Fortune(message) values('People are naturally attracted to you.');
insert into Fortune(message) values('You learn from your mistakes... You will learn a lot today.');
insert into Fortune(message) values('If you have something good in your life, don''t let it go!');
insert into Fortune(message) values('What ever you''re goal is in life, embrace it visualize it, and for it will be yours.');
insert into Fortune(message) values('Your shoes will make you happy today.');
insert into Fortune(message) values('You cannot love life until you live the life you love.');
insert into Fortune(message) values('Be on the lookout for coming events; They cast their shadows beforehand.');
insert into Fortune(message) values('Land is always on the mind of a flying bird.');
insert into Fortune(message) values('The man or woman you desire feels the same about you.');
insert into Fortune(message) values('Meeting adversity well is the source of your strength.');
insert into Fortune(message) values('A dream you have will come true.');
insert into Fortune(message) values('Our deeds determine us, as much as we determine our deeds.');
insert into Fortune(message) values('Never give up. You''re not a failure if you don''t give up.');
insert into Fortune(message) values('You will become great if you believe in yourself.');
insert into Fortune(message) values('There is no greater pleasure than seeing your loved ones prosper.');
insert into Fortune(message) values('You will marry your lover.');
insert into Fortune(message) values('A very attractive person has a message for you.');
insert into Fortune(message) values('You already know the answer to the questions lingering inside your head.');
insert into Fortune(message) values('It is now, and in this world, that we must live.');
insert into Fortune(message) values('You must try, or hate yourself for not trying.');
insert into Fortune(message) values('You can make your own happiness.');
insert into Fortune(message) values('The greatest risk is not taking one.');
insert into Fortune(message) values('The love of your life is stepping into your planet this summer.');
insert into Fortune(message) values('Love can last a lifetime, if you want it to.');
insert into Fortune(message) values('Adversity is the parent of virtue.');
insert into Fortune(message) values('Serious trouble will bypass you.');
insert into Fortune(message) values('A short stranger will soon enter your life with blessings to share.');
insert into Fortune(message) values('Now is the time to try something new.');
insert into Fortune(message) values('Wealth awaits you very soon.');
insert into Fortune(message) values('If you feel you are right, stand firmly by your convictions.');
insert into Fortune(message) values('If winter comes, can spring be far behind?');
insert into Fortune(message) values('Keep your eye out for someone special.');
insert into Fortune(message) values('You are very talented in many ways.');
insert into Fortune(message) values('A stranger, is a friend you have not spoken to yet.');
insert into Fortune(message) values('A new voyage will fill your life with untold memories.');
insert into Fortune(message) values('You will travel to many exotic places in your lifetime.');
insert into Fortune(message) values('Your ability for accomplishment will follow with success.');
insert into Fortune(message) values('Nothing astonishes men so much as common sense and plain dealing.');
insert into Fortune(message) values('Its amazing how much good you can do if you dont care who gets the credit.');
insert into Fortune(message) values('Everyone agrees. You are the best.');
insert into Fortune(message) values('LIFE CONSIST NOT IN HOLDING GOOD CARDS, BUT IN PLAYING THOSE YOU HOLD WELL.');
insert into Fortune(message) values('Jealousy doesn''t open doors, it closes them!');
insert into Fortune(message) values('It''s better to be alone sometimes.');
insert into Fortune(message) values('When fear hurts you, conquer it and defeat it!');
insert into Fortune(message) values('Let the deeds speak.');
insert into Fortune(message) values('You will be called in to fulfill a position of high honor and responsibility.');
insert into Fortune(message) values('The man on the top of the mountain did not fall there.');
insert into Fortune(message) values('You will conquer obstacles to achieve success.');
insert into Fortune(message) values('Joys are often the shadows, cast by sorrows.');
insert into Fortune(message) values('Fortune favors the brave.');

insert into User(firstName, lastName, birthDate) values('Jimi', 'Hendrix', '1948-12-17');
insert into User(firstName, lastName, birthDate) values('Janis', 'Joplin', '1952-07-13');